/// <reference types="node" resolution-mode="require"/>
import { webcrypto } from 'crypto';
/**
 * Import Key from a secure location.
 */
export declare const importedKey: webcrypto.CryptoKey;
/**
 * Encryption and decryption key generated by the AES-GCM algorithm.
 * Saved to a secure location.
 */
export declare function generateKey(): Promise<webcrypto.CryptoKey>;
/**
 * Saves the key to a location.
 * @param key The cryptokey to be saved to a location.
 * @param path The location to save the key to.
 */
export declare function saveKey(key: webcrypto.CryptoKey, path: string): Promise<void>;
/**
 * Loads an AES-GCM encrypt, decrypt key from a location.
 * @param path The location to load the key from.
 * @returns A promise that resolves to the loaded key.
 */
export declare function loadKey(path: string): Promise<webcrypto.CryptoKey>;
//# sourceMappingURL=key.d.ts.map