//Author: Barteld Van Nieuwenhove
//Date: 2023/03/09
import { subtle } from 'crypto';
import fs from 'fs';

const secureLocation = './assets/secure_location/secure_key.txt';

/**
 * Import Key from a secure location.
 */
export const importedKey = await subtle.importKey('raw', fs.readFileSync(secureLocation), 'AES-GCM', true, [
  'encrypt',
  'decrypt',
]);

/**
 * Encryption and decryption key generated by the AES-GCM algorithm.
 * Saved to a secure location.
 */
async function generateAndSaveKey() {
  const key = await subtle.generateKey(
    {
      name: 'AES-GCM',
      length: 256,
    },
    true,
    ['encrypt', 'decrypt']
  );
  const exportedKey = await subtle.exportKey('raw', key);
  fs.writeFileSync(secureLocation, new DataView(exportedKey));
}
